services:
  jupyterlab:
    image: lab3image
    env_file:
      - .env
    ports:
      - "8888:8888"
    volumes:
      - ./:/Lab3
    networks:
      - lab3network

  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - lab3network

volumes:
  postgresdata:

networks:
  lab3network: